name: Rivals
version: '${project.version}'
main: net.sudologic.rivals.Rivals
api-version: '1.20'
author: sudologic
depend:
  - WorldGuard
commands:
  rivals:
    description: Main rivals command
    usage: /rivals